import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv("cleaned_superstore.csv")
print(df.head())
print(df.info())
print(df.describe())
print("\nTotal Sales:", df["Sales"].sum())
print("Average Sales:", df["Sales"].mean())
print("Maximum Profit:", df["Profit"].max())
sales_ctgry = df.groupby("Category")["Sales"].sum()
print("\nSales by Category")
print(sales_ctgry)
profit_rgion = df.groupby("Region")["Profit"].sum()
print("\nProfit by Region")
print(profit_rgion)
top_product = df.groupby("Product Name")["Sales"].sum().sort_values(ascending=False).head(10)
print("\nTop Products")
print(top_product)

sales_ctgry.plot(kind="bar")
plt.xlabel("Category")
plt.ylabel("Sales")
plt.title("Sales by Category")
plt.show()

profit_rgion.plot(kind="bar")
plt.xlabel("Region")
plt.ylabel("Profit")
plt.title("Profit by Region")
plt.show()

top_product.plot(kind="bar")
plt.xlabel("Product Name")
plt.ylabel("Sales")
plt.title("Top 10 Products by Sales")
plt.show()
corr = df[["Sales","Profit","Quantity","Discount"]].corr()
print("\nCorrelation Matrix")
print(corr)